Pandas series is like a column in a table . It is a 1-d array holding data of any type

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
country = ['India','Pakistan','USA','Nepal','Srilanka']
pd.Series(country)

0       India
1    Pakistan
2         USA
3       Nepal
4    Srilanka
dtype: object

In [ ]:
runs = [13,24,56,78,100]
runs_series =pd.Series(runs)

In [ ]:
#custom index
marks = [67,57,89,100]
subjects = ['Maths','Science','English','Hindi']
pd.Series(marks,index=subjects,name = 'Avinash ke Marks')

Maths       67
Science     57
English     89
Hindi      100
Name: Avinash ke Marks, dtype: int64

In [ ]:
marks = {
    'Maths':67,
    'Science':57,
    'English':89,
    'Hindi':100
}
marks_series = pd.Series(marks, name = 'Avinash ke marks')
marks_series

Maths       67
Science     57
English     89
Hindi      100
Name: Avinash ke marks, dtype: int64

Series Attributes

In [ ]:
marks_series.size

4

In [ ]:
marks_series.dtype

dtype('int64')

In [ ]:
marks_series.is_unique

True

In [ ]:
marks_series.index

Index(['Maths', 'Science', 'English', 'Hindi'], dtype='object')

In [ ]:
runs_series.index

RangeIndex(start=0, stop=5, step=1)

In [ ]:
runs_series.values

array([ 13,  24,  56,  78, 100])

In [ ]:
titanic = pd.read_csv('titanic.csv',index_col='PassengerId', squeeze = True)

type(titanic)

TypeError: read_csv() got an unexpected keyword argument 'squeeze'

In [ ]:
pd.DataFrame(titanic)