In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('diabetes.csv')

In [3]:
df

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [4]:
df.corr()['Outcome']

Pregnancies                 0.221898
Glucose                     0.466581
BloodPressure               0.065068
SkinThickness               0.074752
Insulin                     0.130548
BMI                         0.292695
DiabetesPedigreeFunction    0.173844
Age                         0.238356
Outcome                     1.000000
Name: Outcome, dtype: float64

In [5]:
X = df.drop('Outcome', axis=1)
y = df['Outcome']

In [6]:
X = np.array(X)
y = np.array(y)

In [7]:
X

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [9]:
X.shape

(768, 8)

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=1)

In [11]:
import tensorflow as tf
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [12]:
model = Sequential()
model.add(Dense(32, activation='relu', input_dim=8))

model.add(Dense(1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [13]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [14]:
model.compile(optimizer='Adam', loss='binary_crossentropy', metrics=['accuracy'])

In [15]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 20ms/step - accuracy: 0.4463 - loss: 0.7455 - val_accuracy: 0.5000 - val_loss: 0.6988
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6059 - loss: 0.6666 - val_accuracy: 0.6234 - val_loss: 0.6283
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7052 - loss: 0.6102 - val_accuracy: 0.7143 - val_loss: 0.5819
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7264 - loss: 0.5724 - val_accuracy: 0.7532 - val_loss: 0.5473
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7573 - loss: 0.5438 - val_accuracy: 0.7662 - val_loss: 0.5230
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7704 - loss: 0.5228 - val_accuracy: 0.7727 - val_loss: 0.5071
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7818 - loss: 0.5068 - val_accuracy: 0.7922 - val_loss: 0.4929
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4933 - val_accuracy: 0.8052 - val_loss: 0.4829
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4833 - val_accuracy: 0.7987 - val_loss: 0.4759
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4754 - val_accuracy: 0.7987 - val_loss: 0.4705
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4699 - val_accuracy: 0.7857 - val_loss: 0.4659
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4653 - val_accuracy: 0.7857 - val_loss: 0.4640
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4619 - val_accuracy: 0.7857 - val_loss: 0.4633
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4592 - val_accuracy: 0.7857 - val_loss: 0.4629
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4569 - val_accuracy: 0.7857 - val_loss: 0.4619
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4551 - val_accuracy: 0.7857 - val_loss: 0.4608
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4539 - val_accuracy: 0.7792 - val_loss: 0.4599
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4524 - val_accuracy: 0.7792 - val_loss: 0.4599
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4512 - val_accuracy: 0.7792 - val_loss: 0.4587
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4500 - val_accuracy: 0.7857 - val_loss: 0.4592
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4495 - val_accuracy: 0.7922 - val_loss: 0.4599
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4480 - val_accuracy: 0.7922 - val_loss: 0.4595
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4468 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4462 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4456 - val_accuracy: 0.7922 - val_loss: 0.4601
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4455 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4441 - val_accuracy: 0.7987 - val_loss: 0.4611
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7883 - loss: 0.4436 - val_accuracy: 0.7987 - val_loss: 0.4616
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4425 - val_accuracy: 0.7987 - val_loss: 0.4606
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4423 - val_accuracy: 0.7987 - val_loss: 0.4600
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4415 - val_accuracy: 0.7922 - val_loss: 0.4612
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4411 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4408 - val_accuracy: 0.8052 - val_loss: 0.4612
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4403 - val_accuracy: 0.7987 - val_loss: 0.4623
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4400 - val_accuracy: 0.8052 - val_loss: 0.4620
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4393 - val_accuracy: 0.8052 - val_loss: 0.4624
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4391 - val_accuracy: 0.7987 - val_loss: 0.4604
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4386 - val_accuracy: 0.8052 - val_loss: 0.4633
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4376 - val_accuracy: 0.7987 - val_loss: 0.4641
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4371 - val_accuracy: 0.7987 - val_loss: 0.4629
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4373 - val_accuracy: 0.8052 - val_loss: 0.4633
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4368 - val_accuracy: 0.7922 - val_loss: 0.4656
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4365 - val_accuracy: 0.7922 - val_loss: 0.4650
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4366 - val_accuracy: 0.7987 - val_loss: 0.4636
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4350 - val_accuracy: 0.8052 - val_loss: 0.4619
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4345 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4348 - val_accuracy: 0.8052 - val_loss: 0.4609
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4334 - val_accuracy: 0.8052 - val_loss: 0.4605
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4332 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4326 - val_accuracy: 0.8052 - val_loss: 0.4622
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4323 - val_accuracy: 0.8052 - val_loss: 0.4618
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4323 - val_accuracy: 0.8052 - val_loss: 0.4608
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4320 - val_accuracy: 0.8052 - val_loss: 0.4615
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4309 - val_accuracy: 0.7987 - val_loss: 0.4604
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4308 - val_accuracy: 0.8052 - val_loss: 0.4617
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4307 - val_accuracy: 0.8117 - val_loss: 0.4621
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4302 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4302 - val_accuracy: 0.8117 - val_loss: 0.4593
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4292 - val_accuracy: 0.8117 - val_loss: 0.4610
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4298 - val_accuracy: 0.8117 - val_loss: 0.4609
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4287 - val_accuracy: 0.8117 - val_loss: 0.4606
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4286 - val_accuracy: 0.8117 - val_loss: 0.4595
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4278 - val_accuracy: 0.8117 - val_loss: 0.4612
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4273 - val_accuracy: 0.8117 - val_loss: 0.4619
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4276 - val_accuracy: 0.8117 - val_loss: 0.4615
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4268 - val_accuracy: 0.8117 - val_loss: 0.4627
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4264 - val_accuracy: 0.8117 - val_loss: 0.4628
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4266 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4268 - val_accuracy: 0.8117 - val_loss: 0.4638
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4256 - val_accuracy: 0.8117 - val_loss: 0.4635
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4254 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4251 - val_accuracy: 0.8117 - val_loss: 0.4620
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4248 - val_accuracy: 0.8052 - val_loss: 0.4612
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8013 - loss: 0.4243 - val_accuracy: 0.8117 - val_loss: 0.4611
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8046 - loss: 0.4243 - val_accuracy: 0.8117 - val_loss: 0.4618
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4236 - val_accuracy: 0.8117 - val_loss: 0.4624
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4233 - val_accuracy: 0.8117 - val_loss: 0.4607
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4231 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.7948 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4230 - val_accuracy: 0.8117 - val_loss: 0.4622
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7948 - loss: 0.4224 - val_accuracy: 0.8117 - val_loss: 0.4632
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4222 - val_accuracy: 0.8117 - val_loss: 0.4617
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4225 - val_accuracy: 0.8182 - val_loss: 0.4626
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4221 - val_accuracy: 0.8117 - val_loss: 0.4629
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4219 - val_accuracy: 0.8182 - val_loss: 0.4611
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7948 - loss: 0.4209 - val_accuracy: 0.8117 - val_loss: 0.4589
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7964 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4602
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7964 - loss: 0.4210 - val_accuracy: 0.8117 - val_loss: 0.4592
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7980 - loss: 0.4205 - val_accuracy: 0.8117 - val_loss: 0.4606
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4198 - val_accuracy: 0.8117 - val_loss: 0.4597
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4199 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4193 - val_accuracy: 0.8052 - val_loss: 0.4611
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4193 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4190 - val_accuracy: 0.8247 - val_loss: 0.4598
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4193 - val_accuracy: 0.8052 - val_loss: 0.4594
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4189 - val_accuracy: 0.8247 - val_loss: 0.4591
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4182 - val_accuracy: 0.8117 - val_loss: 0.4601
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4181 - val_accuracy: 0.8117 - val_loss: 0.4607
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7964 - loss: 0.4181 - val_accuracy: 0.8117 - val_loss: 0.4610

In [16]:
# 1. How to select appropriate optimizer
# 2. No. of nodes in a layer
# 3. How to select no.of layers
# 4. All in all one model

In [17]:
pip install -U keras-tuner

Collecting keras-tuner
  Downloading keras_tuner-1.4.8-py3-none-any.whl.metadata (5.6 kB)
Requirement already satisfied: keras in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (3.13.2)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (26.2)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (2.32.4)
Collecting kt-legacy (from keras-tuner)
  Downloading kt_legacy-1.0.5-py3-none-any.whl.metadata (221 bytes)
Requirement already satisfied: grpcio in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (1.82.1)
Requirement already satisfied: protobuf in /usr/local/lib/python3.12/dist-packages (from keras-tuner) (5.29.6)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio->keras-tuner) (4.16.0)
Requirement already satisfied: absl-py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (1.4.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (2.0.2)
Requirement already satisfied: rich in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (13.9.4)
Requirement already satisfied: namex in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.1.0)
Requirement already satisfied: h5py in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (3.16.0)
Requirement already satisfied: optree in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.19.1)
Requirement already satisfied: ml-dtypes in /usr/local/lib/python3.12/dist-packages (from keras->keras-tuner) (0.5.4)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.4.9)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (3.18)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->keras-tuner) (2026.6.17)
Requirement already satisfied: markdown-it-py>=2.2.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in /usr/local/lib/python3.12/dist-packages (from rich->keras->keras-tuner) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in /usr/local/lib/python3.12/dist-packages (from markdown-it-py>=2.2.0->rich->keras->keras-tuner) (0.1.2)
Downloading keras_tuner-1.4.8-py3-none-any.whl (129 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 129.4/129.4 kB 4.7 MB/s eta 0:00:00
Downloading kt_legacy-1.0.5-py3-none-any.whl (9.6 kB)
Installing collected packages: kt-legacy, keras-tuner
Successfully installed keras-tuner-1.4.8 kt-legacy-1.0.5

In [18]:
import kerastuner as kt

/tmp/ipykernel_812/1654478174.py:1: DeprecationWarning: `import kerastuner` is deprecated, please use `import keras_tuner`.
  import kerastuner as kt

In [19]:
def build_model(hp):
  model = Sequential()
  model.add(Dense(32, activation='relu', input_dim=8))
  model.add(Dense(1, activation='sigmoid'))

  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [20]:
tuner = kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5)

In [21]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 4 Complete [00h 00m 02s]
val_accuracy: 0.7597402334213257

Best val_accuracy So Far: 0.7727272510528564
Total elapsed time: 00h 00m 10s

In [22]:
tuner.get_best_hyperparameters()[0].values

{'optimizer': 'rmsprop'}

In [23]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 6 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [24]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 32)             │           288 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            33 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 321 (1.25 KB)

 Trainable params: 321 (1.25 KB)

 Non-trainable params: 0 (0.00 B)

In [25]:
model.fit(X_train, y_train, batch_size=32, epochs=100, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step - accuracy: 0.7508 - loss: 0.5760 - val_accuracy: 0.7727 - val_loss: 0.5551
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5540 - val_accuracy: 0.7792 - val_loss: 0.5367
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7671 - loss: 0.5379 - val_accuracy: 0.7922 - val_loss: 0.5206
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.5241 - val_accuracy: 0.7792 - val_loss: 0.5085
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.5116 - val_accuracy: 0.7792 - val_loss: 0.4983
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.5016 - val_accuracy: 0.7727 - val_loss: 0.4906
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7752 - loss: 0.4943 - val_accuracy: 0.7727 - val_loss: 0.4843
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7769 - loss: 0.4875 - val_accuracy: 0.7792 - val_loss: 0.4790
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.4826 - val_accuracy: 0.7792 - val_loss: 0.4755
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7801 - loss: 0.4780 - val_accuracy: 0.7922 - val_loss: 0.4722
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4747 - val_accuracy: 0.7857 - val_loss: 0.4716
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7818 - loss: 0.4719 - val_accuracy: 0.7792 - val_loss: 0.4706
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4699 - val_accuracy: 0.7792 - val_loss: 0.4694
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7818 - loss: 0.4681 - val_accuracy: 0.7792 - val_loss: 0.4685
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7801 - loss: 0.4666 - val_accuracy: 0.7792 - val_loss: 0.4670
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7801 - loss: 0.4646 - val_accuracy: 0.7792 - val_loss: 0.4663
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7850 - loss: 0.4635 - val_accuracy: 0.7857 - val_loss: 0.4653
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4615 - val_accuracy: 0.7792 - val_loss: 0.4652
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4606 - val_accuracy: 0.7792 - val_loss: 0.4645
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7866 - loss: 0.4597 - val_accuracy: 0.7727 - val_loss: 0.4651
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4588 - val_accuracy: 0.7792 - val_loss: 0.4647
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7818 - loss: 0.4580 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7850 - loss: 0.4571 - val_accuracy: 0.7792 - val_loss: 0.4645
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7866 - loss: 0.4562 - val_accuracy: 0.7727 - val_loss: 0.4648
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7883 - loss: 0.4558 - val_accuracy: 0.7792 - val_loss: 0.4649
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4544 - val_accuracy: 0.7792 - val_loss: 0.4643
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4541 - val_accuracy: 0.7792 - val_loss: 0.4644
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4535 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4528 - val_accuracy: 0.7792 - val_loss: 0.4650
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4520 - val_accuracy: 0.7792 - val_loss: 0.4653
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7769 - loss: 0.4519 - val_accuracy: 0.7857 - val_loss: 0.4658
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4510 - val_accuracy: 0.7792 - val_loss: 0.4656
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4507 - val_accuracy: 0.7792 - val_loss: 0.4642
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4503 - val_accuracy: 0.7792 - val_loss: 0.4644
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4501 - val_accuracy: 0.7792 - val_loss: 0.4646
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4493 - val_accuracy: 0.7792 - val_loss: 0.4650
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4487 - val_accuracy: 0.7792 - val_loss: 0.4647
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4483 - val_accuracy: 0.7792 - val_loss: 0.4650
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4479 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4478 - val_accuracy: 0.7922 - val_loss: 0.4643
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4472 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4465 - val_accuracy: 0.7922 - val_loss: 0.4640
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7834 - loss: 0.4467 - val_accuracy: 0.7857 - val_loss: 0.4636
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7883 - loss: 0.4457 - val_accuracy: 0.7857 - val_loss: 0.4627
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4457 - val_accuracy: 0.7922 - val_loss: 0.4616
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4453 - val_accuracy: 0.7857 - val_loss: 0.4620
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.4447 - val_accuracy: 0.7987 - val_loss: 0.4614
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4443 - val_accuracy: 0.7922 - val_loss: 0.4620
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7834 - loss: 0.4443 - val_accuracy: 0.7922 - val_loss: 0.4623
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7801 - loss: 0.4436 - val_accuracy: 0.7922 - val_loss: 0.4628
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7866 - loss: 0.4430 - val_accuracy: 0.7857 - val_loss: 0.4636
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7785 - loss: 0.4427 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7850 - loss: 0.4426 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7850 - loss: 0.4423 - val_accuracy: 0.7857 - val_loss: 0.4630
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4415 - val_accuracy: 0.7857 - val_loss: 0.4636
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7818 - loss: 0.4413 - val_accuracy: 0.7922 - val_loss: 0.4636
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4416 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4407 - val_accuracy: 0.7922 - val_loss: 0.4633
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4405 - val_accuracy: 0.7922 - val_loss: 0.4637
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4397 - val_accuracy: 0.7857 - val_loss: 0.4632
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4398 - val_accuracy: 0.7922 - val_loss: 0.4629
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7801 - loss: 0.4393 - val_accuracy: 0.7857 - val_loss: 0.4622
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4391 - val_accuracy: 0.7987 - val_loss: 0.4609
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4383 - val_accuracy: 0.7857 - val_loss: 0.4608
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4381 - val_accuracy: 0.7987 - val_loss: 0.4603
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4382 - val_accuracy: 0.7987 - val_loss: 0.4613
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4379 - val_accuracy: 0.7922 - val_loss: 0.4611
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4374 - val_accuracy: 0.8052 - val_loss: 0.4603
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4367 - val_accuracy: 0.7987 - val_loss: 0.4605
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4365 - val_accuracy: 0.7922 - val_loss: 0.4609
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4360 - val_accuracy: 0.7987 - val_loss: 0.4612
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4360 - val_accuracy: 0.7922 - val_loss: 0.4610
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4361 - val_accuracy: 0.7922 - val_loss: 0.4608
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7915 - loss: 0.4350 - val_accuracy: 0.7987 - val_loss: 0.4588
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7866 - loss: 0.4351 - val_accuracy: 0.7987 - val_loss: 0.4581
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4347 - val_accuracy: 0.7987 - val_loss: 0.4587
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7932 - loss: 0.4347 - val_accuracy: 0.8052 - val_loss: 0.4582
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7899 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4569
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7883 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4572
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4338 - val_accuracy: 0.8052 - val_loss: 0.4573
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7850 - loss: 0.4328 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4330 - val_accuracy: 0.7987 - val_loss: 0.4577
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4323 - val_accuracy: 0.7987 - val_loss: 0.4569
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4324 - val_accuracy: 0.7987 - val_loss: 0.4566
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7932 - loss: 0.4318 - val_accuracy: 0.7987 - val_loss: 0.4551
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4315 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4309 - val_accuracy: 0.8052 - val_loss: 0.4546
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7915 - loss: 0.4309 - val_accuracy: 0.8117 - val_loss: 0.4546
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7997 - loss: 0.4305 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7899 - loss: 0.4301 - val_accuracy: 0.8052 - val_loss: 0.4544
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7932 - loss: 0.4299 - val_accuracy: 0.8052 - val_loss: 0.4541
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7915 - loss: 0.4300 - val_accuracy: 0.8052 - val_loss: 0.4539
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7964 - loss: 0.4297 - val_accuracy: 0.7987 - val_loss: 0.4544
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7948 - loss: 0.4286 - val_accuracy: 0.8052 - val_loss: 0.4531
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7948 - loss: 0.4286 - val_accuracy: 0.8052 - val_loss: 0.4517
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7980 - loss: 0.4281 - val_accuracy: 0.8052 - val_loss: 0.4518
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.8029 - loss: 0.4278 - val_accuracy: 0.7987 - val_loss: 0.4521
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7980 - loss: 0.4272 - val_accuracy: 0.8052 - val_loss: 0.4514
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7997 - loss: 0.4271 - val_accuracy: 0.8117 - val_loss: 0.4516
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7932 - loss: 0.4269 - val_accuracy: 0.8052 - val_loss: 0.4519

# 2. No. of nodes in a layer

In [26]:
def build_model(hp):

  model = Sequential()

  units = hp.Int(8,128,step = 8)

  model.add(Dense(units, activation='relu', input_dim=8))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [27]:
def build_model(hp):
  model = Sequential()
  # The first argument to hp.Int must be a string 'name'.
  # The other arguments are min_value, max_value, and step.
  units = hp.Int('units', min_value=8, max_value=128)
  model.add(Dense(units, activation='relu', input_dim=8))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

tuner = kt.RandomSearch(build_model,
                      objective='val_accuracy',
                      max_trials=5,
                      directory ='mydir',
                      project_name = 'Selmon')

In [28]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 5 Complete [00h 00m 02s]
val_accuracy: 0.7272727489471436

Best val_accuracy So Far: 0.7922077775001526
Total elapsed time: 00h 00m 12s

In [29]:
tuner.get_best_hyperparameters()[0].values

{'units': 27, 'optimizer': 'adam'}

In [30]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'adam', because it has 2 variables whereas the saved optimizer has 10 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [31]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 27)             │           243 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            28 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 271 (1.06 KB)

 Trainable params: 271 (1.06 KB)

 Non-trainable params: 0 (0.00 B)

# 3. How to select no.of layers

In [32]:
def build_model(hp):
  model = Sequential()
  # The first argument to hp.Int must be a string 'name'.

  model.add(Dense(72, activation='relu', input_dim=8))

  for i in range(hp.Int('num_layers',min_value=1,max_value=10)):
    model.add(Dense(72, activation='relu'))

  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [33]:
tuner = kt.RandomSearch(build_model,
                        objective = 'val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name = 'num_layers')

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [34]:
tuner.search(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.8116883039474487

Best val_accuracy So Far: 0.8116883039474487
Total elapsed time: 00h 00m 13s

In [35]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 8, 'optimizer': 'rmsprop'}

In [36]:
model = tuner.get_best_models(num_models=1)[0]

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)
/usr/local/lib/python3.12/dist-packages/keras/src/saving/saving_lib.py:797: UserWarning: Skipping variable loading for optimizer 'rmsprop', because it has 2 variables whereas the saved optimizer has 22 variables.
  saveable.load_own_variables(weights_store.get(inner_path))

In [37]:
model.fit(X_train, y_train, epochs=100,initial_epoch = 6, validation_data=(X_test, y_test))

Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 2s 19ms/step - accuracy: 0.7638 - loss: 0.4740 - val_accuracy: 0.7597 - val_loss: 0.4702
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7850 - loss: 0.4420 - val_accuracy: 0.7922 - val_loss: 0.4843
Epoch 9/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7964 - loss: 0.4359 - val_accuracy: 0.7727 - val_loss: 0.4766
Epoch 10/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8208 - loss: 0.4199 - val_accuracy: 0.7013 - val_loss: 0.5988
Epoch 11/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8094 - loss: 0.4164 - val_accuracy: 0.7403 - val_loss: 0.5489
Epoch 12/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8062 - loss: 0.4081 - val_accuracy: 0.7662 - val_loss: 0.4898
Epoch 13/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8225 - loss: 0.4018 - val_accuracy: 0.7662 - val_loss: 0.5384
Epoch 14/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8355 - loss: 0.3809 - val_accuracy: 0.7597 - val_loss: 0.4992
Epoch 15/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8257 - loss: 0.3849 - val_accuracy: 0.7597 - val_loss: 0.5326
Epoch 16/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8436 - loss: 0.3690 - val_accuracy: 0.7857 - val_loss: 0.5016
Epoch 17/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8371 - loss: 0.3496 - val_accuracy: 0.7532 - val_loss: 0.5653
Epoch 18/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.8583 - loss: 0.3463 - val_accuracy: 0.7792 - val_loss: 0.5335
Epoch 19/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8616 - loss: 0.3308 - val_accuracy: 0.7338 - val_loss: 0.5860
Epoch 20/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8502 - loss: 0.3264 - val_accuracy: 0.7532 - val_loss: 0.5841
Epoch 21/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8795 - loss: 0.3139 - val_accuracy: 0.7532 - val_loss: 0.6035
Epoch 22/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8664 - loss: 0.3081 - val_accuracy: 0.7403 - val_loss: 0.6290
Epoch 23/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8681 - loss: 0.3017 - val_accuracy: 0.7208 - val_loss: 0.7048
Epoch 24/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8648 - loss: 0.3090 - val_accuracy: 0.7597 - val_loss: 0.6004
Epoch 25/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8730 - loss: 0.2811 - val_accuracy: 0.7403 - val_loss: 0.6934
Epoch 26/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8893 - loss: 0.2703 - val_accuracy: 0.6818 - val_loss: 0.6678
Epoch 27/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8990 - loss: 0.2646 - val_accuracy: 0.7662 - val_loss: 0.7449
Epoch 28/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.8974 - loss: 0.2427 - val_accuracy: 0.7403 - val_loss: 0.9218
Epoch 29/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.8974 - loss: 0.2516 - val_accuracy: 0.7403 - val_loss: 0.7466
Epoch 30/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9202 - loss: 0.2219 - val_accuracy: 0.7662 - val_loss: 0.7744
Epoch 31/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9202 - loss: 0.2017 - val_accuracy: 0.7338 - val_loss: 0.8505
Epoch 32/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9088 - loss: 0.2171 - val_accuracy: 0.6623 - val_loss: 1.1225
Epoch 33/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9202 - loss: 0.2069 - val_accuracy: 0.7273 - val_loss: 0.8773
Epoch 34/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9430 - loss: 0.1697 - val_accuracy: 0.7208 - val_loss: 0.9706
Epoch 35/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9430 - loss: 0.1577 - val_accuracy: 0.7273 - val_loss: 0.9835
Epoch 36/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9202 - loss: 0.2031 - val_accuracy: 0.7403 - val_loss: 0.9173
Epoch 37/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9446 - loss: 0.1513 - val_accuracy: 0.7792 - val_loss: 0.9690
Epoch 38/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9463 - loss: 0.1515 - val_accuracy: 0.7338 - val_loss: 0.9441
Epoch 39/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9430 - loss: 0.1509 - val_accuracy: 0.7468 - val_loss: 0.9818
Epoch 40/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9577 - loss: 0.1262 - val_accuracy: 0.7727 - val_loss: 1.0586
Epoch 41/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9463 - loss: 0.1394 - val_accuracy: 0.7532 - val_loss: 1.1316
Epoch 42/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9446 - loss: 0.1229 - val_accuracy: 0.7403 - val_loss: 1.3179
Epoch 43/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1169 - val_accuracy: 0.7273 - val_loss: 1.4839
Epoch 44/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1128 - val_accuracy: 0.7338 - val_loss: 1.2306
Epoch 45/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9544 - loss: 0.1309 - val_accuracy: 0.6688 - val_loss: 1.4818
Epoch 46/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9593 - loss: 0.1013 - val_accuracy: 0.7208 - val_loss: 1.2649
Epoch 47/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9593 - loss: 0.1155 - val_accuracy: 0.7013 - val_loss: 1.2129
Epoch 48/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9691 - loss: 0.0868 - val_accuracy: 0.7338 - val_loss: 1.2267
Epoch 49/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9691 - loss: 0.0974 - val_accuracy: 0.7403 - val_loss: 1.2720
Epoch 50/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.0853 - val_accuracy: 0.7078 - val_loss: 1.4184
Epoch 51/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9495 - loss: 0.1496 - val_accuracy: 0.7273 - val_loss: 1.1477
Epoch 52/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0627 - val_accuracy: 0.7273 - val_loss: 1.3492
Epoch 53/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9723 - loss: 0.0846 - val_accuracy: 0.7273 - val_loss: 1.3767
Epoch 54/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9821 - loss: 0.0558 - val_accuracy: 0.7468 - val_loss: 1.7154
Epoch 55/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0741 - val_accuracy: 0.7013 - val_loss: 1.7735
Epoch 56/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9788 - loss: 0.0786 - val_accuracy: 0.7597 - val_loss: 1.3934
Epoch 57/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0449 - val_accuracy: 0.7532 - val_loss: 1.6535
Epoch 58/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9772 - loss: 0.0725 - val_accuracy: 0.6948 - val_loss: 1.9139
Epoch 59/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0379 - val_accuracy: 0.7013 - val_loss: 1.9308
Epoch 60/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9674 - loss: 0.0885 - val_accuracy: 0.7792 - val_loss: 1.5878
Epoch 61/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9853 - loss: 0.0579 - val_accuracy: 0.7078 - val_loss: 1.7272
Epoch 62/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0869 - val_accuracy: 0.7143 - val_loss: 1.4911
Epoch 63/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0341 - val_accuracy: 0.7468 - val_loss: 1.7055
Epoch 64/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0320 - val_accuracy: 0.7273 - val_loss: 1.7031
Epoch 65/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9853 - loss: 0.0664 - val_accuracy: 0.7273 - val_loss: 1.6734
Epoch 66/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9691 - loss: 0.0892 - val_accuracy: 0.6883 - val_loss: 1.6354
Epoch 67/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0277 - val_accuracy: 0.7403 - val_loss: 1.8197
Epoch 68/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0188 - val_accuracy: 0.7468 - val_loss: 1.9645
Epoch 69/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9837 - loss: 0.0564 - val_accuracy: 0.7078 - val_loss: 1.7906
Epoch 70/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9902 - loss: 0.0271 - val_accuracy: 0.7143 - val_loss: 2.2218
Epoch 71/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9805 - loss: 0.0674 - val_accuracy: 0.7403 - val_loss: 1.7056
Epoch 72/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9951 - loss: 0.0093 - val_accuracy: 0.7338 - val_loss: 2.1232
Epoch 73/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9853 - loss: 0.0781 - val_accuracy: 0.7403 - val_loss: 1.8628
Epoch 74/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9935 - loss: 0.0289 - val_accuracy: 0.7403 - val_loss: 1.8907
Epoch 75/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9870 - loss: 0.0483 - val_accuracy: 0.7532 - val_loss: 1.9947
Epoch 76/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9886 - loss: 0.0489 - val_accuracy: 0.7143 - val_loss: 1.6120
Epoch 77/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9902 - loss: 0.0341 - val_accuracy: 0.7468 - val_loss: 1.9318
Epoch 78/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9919 - loss: 0.0445 - val_accuracy: 0.7403 - val_loss: 1.8022
Epoch 79/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9886 - loss: 0.0462 - val_accuracy: 0.7403 - val_loss: 1.6949
Epoch 80/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0085 - val_accuracy: 0.7273 - val_loss: 2.0578
Epoch 81/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9788 - loss: 0.0753 - val_accuracy: 0.7468 - val_loss: 1.8266
Epoch 82/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0633 - val_accuracy: 0.7403 - val_loss: 1.6203
Epoch 83/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9984 - loss: 0.0091 - val_accuracy: 0.7403 - val_loss: 1.9584
Epoch 84/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9772 - loss: 0.0648 - val_accuracy: 0.7468 - val_loss: 1.9201
Epoch 85/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0278 - val_accuracy: 0.6883 - val_loss: 1.9491
Epoch 86/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9902 - loss: 0.0285 - val_accuracy: 0.7078 - val_loss: 1.8231
Epoch 87/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9870 - loss: 0.0376 - val_accuracy: 0.7208 - val_loss: 1.8676
Epoch 88/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.9967 - loss: 0.0156 - val_accuracy: 0.7403 - val_loss: 1.9282
Epoch 89/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9821 - loss: 0.0402 - val_accuracy: 0.7338 - val_loss: 2.0127
Epoch 90/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9935 - loss: 0.0217 - val_accuracy: 0.7143 - val_loss: 2.1066
Epoch 91/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0020 - val_accuracy: 0.7013 - val_loss: 3.2481
Epoch 92/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.9805 - loss: 0.0724 - val_accuracy: 0.7468 - val_loss: 2.1385
Epoch 93/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9951 - loss: 0.0213 - val_accuracy: 0.7273 - val_loss: 2.0020
Epoch 94/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0015 - val_accuracy: 0.7273 - val_loss: 2.2454
Epoch 95/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 5.7123e-04 - val_accuracy: 0.7273 - val_loss: 2.5110
Epoch 96/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 2.4828e-04 - val_accuracy: 0.7338 - val_loss: 2.7280
Epoch 97/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9984 - loss: 0.0028 - val_accuracy: 0.6948 - val_loss: 3.5374
Epoch 98/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9886 - loss: 0.0512 - val_accuracy: 0.7468 - val_loss: 2.2330
Epoch 99/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9935 - loss: 0.0267 - val_accuracy: 0.7338 - val_loss: 2.2504
Epoch 100/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9919 - loss: 0.0268 - val_accuracy: 0.7208 - val_loss: 2.1834

In [73]:
from keras.layers import Dropout

In [75]:
def build_model(hp):
  model = Sequential()
  counter = 0

  for i in range(hp.Int('num_layers', min_value = 1, max_value =10)):
    if counter == 0:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value = 8, max_value = 128, step = 8),
              activation = hp.Choice('activation'+str(i), values = ['relu','tanh','sigmoid']),
              input_dim = 8))
      model.add(Dropout(hp.Choice('dropout'+str(i), values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))
    else:
      model.add(
          Dense(
              hp.Int('units'+str(i), min_value = 8, max_value = 128, step = 8),
              activation = hp.Choice('activation'+str(i), values = ['relu','tanh','sigmoid']),
              ))
      model.add(Dropout(hp.Choice('dropout'+str(i), values = [0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,0.9])))

    counter += 1
  model.add(Dense(1, activation='sigmoid'))
  model.compile(optimizer=hp.Choice('optimizer',values = ['adam','sgd','rmsprop','adadelta']), loss='binary_crossentropy', metrics=['accuracy'])
  return model

In [78]:
tuner = kt.RandomSearch(build_model,
                        objective ='val_accuracy',
                        max_trials = 3,
                        directory = 'mydir',
                        project_name= 'final2')

In [79]:
tuner.search(X_train, y_train, epochs = 5, validation_data = (X_test, y_test))

Trial 3 Complete [00h 00m 04s]
val_accuracy: 0.7467532753944397

Best val_accuracy So Far: 0.7467532753944397
Total elapsed time: 00h 00m 14s

In [80]:
tuner.get_best_hyperparameters()[0].values

{'num_layers': 2,
 'units0': 32,
 'activation0': 'tanh',
 'dropout0': 0.4,
 'optimizer': 'sgd',
 'units1': 80,
 'activation1': 'tanh',
 'dropout1': 0.8,
 'units2': 72,
 'activation2': 'tanh',
 'dropout2': 0.1,
 'units3': 64,
 'activation3': 'tanh',
 'dropout3': 0.1,
 'units4': 104,
 'activation4': 'tanh',
 'dropout4': 0.2,
 'units5': 104,
 'activation5': 'sigmoid',
 'dropout5': 0.2,
 'units6': 104,
 'activation6': 'sigmoid',
 'dropout6': 0.1,
 'units7': 48,
 'activation7': 'sigmoid',
 'dropout7': 0.9,
 'units8': 40,
 'activation8': 'tanh',
 'dropout8': 0.3,
 'units9': 48,
 'activation9': 'relu',
 'dropout9': 0.6}

In [81]:
model = tuner.get_best_models(num_models=1)[0]

In [82]:
model.fit(X_train, y_train, epochs=200,initial_epoch = 11, validation_data=(X_test, y_test))

Epoch 12/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step - accuracy: 0.6645 - loss: 0.6345 - val_accuracy: 0.7532 - val_loss: 0.5576
Epoch 13/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6417 - loss: 0.6542 - val_accuracy: 0.7597 - val_loss: 0.5456
Epoch 14/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.6531 - loss: 0.6268 - val_accuracy: 0.7662 - val_loss: 0.5345
Epoch 15/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6612 - loss: 0.6119 - val_accuracy: 0.7792 - val_loss: 0.5260
Epoch 16/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6922 - loss: 0.5951 - val_accuracy: 0.7792 - val_loss: 0.5186
Epoch 17/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.6824 - loss: 0.5991 - val_accuracy: 0.7727 - val_loss: 0.5128
Epoch 18/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.6759 - loss: 0.6145 - val_accuracy: 0.7727 - val_loss: 0.5088
Epoch 19/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7085 - loss: 0.5809 - val_accuracy: 0.7792 - val_loss: 0.5039
Epoch 20/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7003 - loss: 0.5745 - val_accuracy: 0.7792 - val_loss: 0.4995
Epoch 21/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5792 - val_accuracy: 0.7792 - val_loss: 0.4958
Epoch 22/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7101 - loss: 0.5674 - val_accuracy: 0.7792 - val_loss: 0.4930
Epoch 23/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5577 - val_accuracy: 0.7727 - val_loss: 0.4900
Epoch 24/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5756 - val_accuracy: 0.7792 - val_loss: 0.4876
Epoch 25/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7166 - loss: 0.5492 - val_accuracy: 0.7727 - val_loss: 0.4859
Epoch 26/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7117 - loss: 0.5439 - val_accuracy: 0.7792 - val_loss: 0.4840
Epoch 27/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7052 - loss: 0.5789 - val_accuracy: 0.7727 - val_loss: 0.4827
Epoch 28/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7020 - loss: 0.5445 - val_accuracy: 0.7727 - val_loss: 0.4806
Epoch 29/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7166 - loss: 0.5546 - val_accuracy: 0.7792 - val_loss: 0.4786
Epoch 30/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5459 - val_accuracy: 0.7727 - val_loss: 0.4771
Epoch 31/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7264 - loss: 0.5237 - val_accuracy: 0.7792 - val_loss: 0.4763
Epoch 32/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7280 - loss: 0.5354 - val_accuracy: 0.7792 - val_loss: 0.4757
Epoch 33/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7036 - loss: 0.5477 - val_accuracy: 0.7727 - val_loss: 0.4744
Epoch 34/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7085 - loss: 0.5545 - val_accuracy: 0.7727 - val_loss: 0.4737
Epoch 35/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5273 - val_accuracy: 0.7727 - val_loss: 0.4731
Epoch 36/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5559 - val_accuracy: 0.7662 - val_loss: 0.4728
Epoch 37/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7313 - loss: 0.5356 - val_accuracy: 0.7597 - val_loss: 0.4717
Epoch 38/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7313 - loss: 0.5454 - val_accuracy: 0.7597 - val_loss: 0.4713
Epoch 39/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7231 - loss: 0.5507 - val_accuracy: 0.7597 - val_loss: 0.4714
Epoch 40/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7476 - loss: 0.5190 - val_accuracy: 0.7597 - val_loss: 0.4707
Epoch 41/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7134 - loss: 0.5447 - val_accuracy: 0.7597 - val_loss: 0.4712
Epoch 42/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5463 - val_accuracy: 0.7662 - val_loss: 0.4714
Epoch 43/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5269 - val_accuracy: 0.7662 - val_loss: 0.4707
Epoch 44/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7296 - loss: 0.5341 - val_accuracy: 0.7662 - val_loss: 0.4700
Epoch 45/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5290 - val_accuracy: 0.7662 - val_loss: 0.4696
Epoch 46/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7166 - loss: 0.5244 - val_accuracy: 0.7662 - val_loss: 0.4688
Epoch 47/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7052 - loss: 0.5555 - val_accuracy: 0.7662 - val_loss: 0.4693
Epoch 48/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5136 - val_accuracy: 0.7662 - val_loss: 0.4689
Epoch 49/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7476 - loss: 0.5319 - val_accuracy: 0.7662 - val_loss: 0.4688
Epoch 50/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7248 - loss: 0.5390 - val_accuracy: 0.7662 - val_loss: 0.4681
Epoch 51/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7394 - loss: 0.5167 - val_accuracy: 0.7662 - val_loss: 0.4679
Epoch 52/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7231 - loss: 0.5131 - val_accuracy: 0.7662 - val_loss: 0.4678
Epoch 53/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7296 - loss: 0.5335 - val_accuracy: 0.7662 - val_loss: 0.4677
Epoch 54/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7508 - loss: 0.5150 - val_accuracy: 0.7662 - val_loss: 0.4670
Epoch 55/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5097 - val_accuracy: 0.7662 - val_loss: 0.4659
Epoch 56/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.5229 - val_accuracy: 0.7662 - val_loss: 0.4661
Epoch 57/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7476 - loss: 0.4985 - val_accuracy: 0.7662 - val_loss: 0.4662
Epoch 58/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5182 - val_accuracy: 0.7662 - val_loss: 0.4664
Epoch 59/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.5137 - val_accuracy: 0.7662 - val_loss: 0.4658
Epoch 60/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7248 - loss: 0.5225 - val_accuracy: 0.7662 - val_loss: 0.4655
Epoch 61/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.5241 - val_accuracy: 0.7662 - val_loss: 0.4657
Epoch 62/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7459 - loss: 0.5219 - val_accuracy: 0.7597 - val_loss: 0.4657
Epoch 63/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7329 - loss: 0.5147 - val_accuracy: 0.7597 - val_loss: 0.4655
Epoch 64/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5080 - val_accuracy: 0.7662 - val_loss: 0.4648
Epoch 65/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7313 - loss: 0.5262 - val_accuracy: 0.7662 - val_loss: 0.4662
Epoch 66/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.5161 - val_accuracy: 0.7662 - val_loss: 0.4657
Epoch 67/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5206 - val_accuracy: 0.7727 - val_loss: 0.4654
Epoch 68/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5252 - val_accuracy: 0.7727 - val_loss: 0.4655
Epoch 69/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5115 - val_accuracy: 0.7727 - val_loss: 0.4647
Epoch 70/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5029 - val_accuracy: 0.7727 - val_loss: 0.4648
Epoch 71/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.5203 - val_accuracy: 0.7727 - val_loss: 0.4645
Epoch 72/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5284 - val_accuracy: 0.7727 - val_loss: 0.4649
Epoch 73/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5043 - val_accuracy: 0.7727 - val_loss: 0.4643
Epoch 74/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7410 - loss: 0.5167 - val_accuracy: 0.7727 - val_loss: 0.4638
Epoch 75/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7378 - loss: 0.5195 - val_accuracy: 0.7727 - val_loss: 0.4637
Epoch 76/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step - accuracy: 0.7394 - loss: 0.5209 - val_accuracy: 0.7727 - val_loss: 0.4639
Epoch 77/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4963 - val_accuracy: 0.7727 - val_loss: 0.4634
Epoch 78/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5004 - val_accuracy: 0.7727 - val_loss: 0.4630
Epoch 79/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5099 - val_accuracy: 0.7727 - val_loss: 0.4630
Epoch 80/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4888 - val_accuracy: 0.7727 - val_loss: 0.4628
Epoch 81/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5085 - val_accuracy: 0.7727 - val_loss: 0.4625
Epoch 82/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7362 - loss: 0.5181 - val_accuracy: 0.7727 - val_loss: 0.4623
Epoch 83/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5083 - val_accuracy: 0.7792 - val_loss: 0.4619
Epoch 84/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7427 - loss: 0.5148 - val_accuracy: 0.7727 - val_loss: 0.4618
Epoch 85/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5027 - val_accuracy: 0.7727 - val_loss: 0.4616
Epoch 86/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5124 - val_accuracy: 0.7792 - val_loss: 0.4620
Epoch 87/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.5048 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 88/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4972 - val_accuracy: 0.7792 - val_loss: 0.4615
Epoch 89/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7231 - loss: 0.5169 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 90/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.5091 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 91/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7443 - loss: 0.5183 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 92/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7622 - loss: 0.4916 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 93/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4992 - val_accuracy: 0.7792 - val_loss: 0.4601
Epoch 94/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7606 - loss: 0.5044 - val_accuracy: 0.7792 - val_loss: 0.4603
Epoch 95/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7590 - loss: 0.4948 - val_accuracy: 0.7792 - val_loss: 0.4603
Epoch 96/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7492 - loss: 0.5206 - val_accuracy: 0.7792 - val_loss: 0.4607
Epoch 97/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.7590 - loss: 0.5039 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 98/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7590 - loss: 0.5063 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 99/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.5039 - val_accuracy: 0.7857 - val_loss: 0.4604
Epoch 100/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7573 - loss: 0.5028 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 101/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7687 - loss: 0.4927 - val_accuracy: 0.7857 - val_loss: 0.4607
Epoch 102/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7508 - loss: 0.5051 - val_accuracy: 0.7857 - val_loss: 0.4610
Epoch 103/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7524 - loss: 0.5196 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 104/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7638 - loss: 0.5058 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 105/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7459 - loss: 0.5063 - val_accuracy: 0.7857 - val_loss: 0.4622
Epoch 106/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7622 - loss: 0.4929 - val_accuracy: 0.7857 - val_loss: 0.4618
Epoch 107/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5104 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 108/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5081 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 109/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.5173 - val_accuracy: 0.7857 - val_loss: 0.4621
Epoch 110/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5013 - val_accuracy: 0.7857 - val_loss: 0.4617
Epoch 111/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7410 - loss: 0.5018 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 112/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5008 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 113/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 0.7541 - loss: 0.5067 - val_accuracy: 0.7857 - val_loss: 0.4616
Epoch 114/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4937 - val_accuracy: 0.7792 - val_loss: 0.4615
Epoch 115/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7606 - loss: 0.5004 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 116/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7557 - loss: 0.4851 - val_accuracy: 0.7792 - val_loss: 0.4607
Epoch 117/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7459 - loss: 0.5089 - val_accuracy: 0.7792 - val_loss: 0.4606
Epoch 118/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5085 - val_accuracy: 0.7792 - val_loss: 0.4605
Epoch 119/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4873 - val_accuracy: 0.7792 - val_loss: 0.4602
Epoch 120/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.5070 - val_accuracy: 0.7727 - val_loss: 0.4606
Epoch 121/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.5043 - val_accuracy: 0.7727 - val_loss: 0.4604
Epoch 122/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.5016 - val_accuracy: 0.7727 - val_loss: 0.4603
Epoch 123/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.4951 - val_accuracy: 0.7727 - val_loss: 0.4601
Epoch 124/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7785 - loss: 0.5090 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 125/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7459 - loss: 0.4973 - val_accuracy: 0.7727 - val_loss: 0.4613
Epoch 126/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5128 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 127/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4921 - val_accuracy: 0.7727 - val_loss: 0.4613
Epoch 128/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7508 - loss: 0.5176 - val_accuracy: 0.7727 - val_loss: 0.4612
Epoch 129/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5026 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 130/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5047 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 131/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7590 - loss: 0.5024 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 132/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7704 - loss: 0.4893 - val_accuracy: 0.7792 - val_loss: 0.4607
Epoch 133/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7752 - loss: 0.5011 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 134/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7492 - loss: 0.5143 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 135/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4882 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 136/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7720 - loss: 0.4745 - val_accuracy: 0.7792 - val_loss: 0.4606
Epoch 137/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7541 - loss: 0.4998 - val_accuracy: 0.7792 - val_loss: 0.4604
Epoch 138/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5026 - val_accuracy: 0.7792 - val_loss: 0.4606
Epoch 139/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5068 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 140/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7394 - loss: 0.4993 - val_accuracy: 0.7792 - val_loss: 0.4612
Epoch 141/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4950 - val_accuracy: 0.7727 - val_loss: 0.4609
Epoch 142/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7704 - loss: 0.4878 - val_accuracy: 0.7792 - val_loss: 0.4605
Epoch 143/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7524 - loss: 0.5023 - val_accuracy: 0.7792 - val_loss: 0.4608
Epoch 144/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7557 - loss: 0.5091 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 145/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.4843 - val_accuracy: 0.7792 - val_loss: 0.4610
Epoch 146/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7671 - loss: 0.5123 - val_accuracy: 0.7792 - val_loss: 0.4616
Epoch 147/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.4931 - val_accuracy: 0.7792 - val_loss: 0.4619
Epoch 148/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7638 - loss: 0.4840 - val_accuracy: 0.7792 - val_loss: 0.4617
Epoch 149/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.5094 - val_accuracy: 0.7727 - val_loss: 0.4613
Epoch 150/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4867 - val_accuracy: 0.7727 - val_loss: 0.4608
Epoch 151/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7573 - loss: 0.4898 - val_accuracy: 0.7727 - val_loss: 0.4614
Epoch 152/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7655 - loss: 0.4844 - val_accuracy: 0.7727 - val_loss: 0.4610
Epoch 153/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7606 - loss: 0.5124 - val_accuracy: 0.7727 - val_loss: 0.4615
Epoch 154/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7443 - loss: 0.5038 - val_accuracy: 0.7727 - val_loss: 0.4611
Epoch 155/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7720 - loss: 0.4889 - val_accuracy: 0.7792 - val_loss: 0.4611
Epoch 156/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7736 - loss: 0.4883 - val_accuracy: 0.7792 - val_loss: 0.4608
Epoch 157/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4812 - val_accuracy: 0.7792 - val_loss: 0.4611
Epoch 158/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4859 - val_accuracy: 0.7792 - val_loss: 0.4609
Epoch 159/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7655 - loss: 0.4911 - val_accuracy: 0.7727 - val_loss: 0.4608
Epoch 160/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.5105 - val_accuracy: 0.7792 - val_loss: 0.4611
Epoch 161/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.7541 - loss: 0.5039 - val_accuracy: 0.7792 - val_loss: 0.4613
Epoch 162/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7590 - loss: 0.4903 - val_accuracy: 0.7792 - val_loss: 0.4615
Epoch 163/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7573 - loss: 0.4953 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 164/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7687 - loss: 0.4883 - val_accuracy: 0.7792 - val_loss: 0.4618
Epoch 165/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7524 - loss: 0.5020 - val_accuracy: 0.7792 - val_loss: 0.4619
Epoch 166/200
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.7671 - loss: 0.4943 - val_accuracy: 0.7792 - val_loss: 0.4619
Epoch 167/200